### PR TITLE
Make project compatible with Node 0.11 and io.js

### PR DESCRIPTION
**Pull request by sdepold**
By updating nan to the latest version, the project will be compatible
with Node.JS 0.11.x and io.js 1.0.2.

### CODE REVIEW

**Comment by sdepold** [comment]
This PR fixes #14, #19# and #20. Pinging https://github.com/iojs/io.js/issues/456

**Comment by XadillaX** [comment]
Anyone to merge this PR?

**Comment by yanana** [comment]
Ping

**Comment by godsflaw** [comment]
merged, version bumped, tagged/signed, and published to npm

**Comment by sdepold** [comment]
Thanks!!!!

**Pull request merged**
